version: '3.8'

services:
  flask-app:
    container_name: flask_app
    build: .
    ports:
      - "5010:5000"
    networks:
      - flask_network
    environment:
      - FLASK_ENV=development
    volumes:
        - .:/app
networks:
  flask_network:
